In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Default_Fin.csv')

In [3]:
df.head()

   Index  Employed  Bank Balance  Annual Salary  Defaulted?
0      1         1       8754.36      532339.56           0
1      2         0       9806.16      145273.56           0
2      3         1      12882.60      381205.68           0
3      4         1       6351.00      428453.88           0
4      5         1       9427.92      461562.00           0

In [4]:
df.isnull().mean()*100

Index            0.0
Employed         0.0
Bank Balance     0.0
Annual Salary    0.0
Defaulted?       0.0
dtype: float64

In [5]:
df.shape

(10000, 5)

In [6]:
df.describe()

             Index      Employed  Bank Balance  Annual Salary    Defaulted?
count  10000.00000  10000.000000  10000.000000   10000.000000  10000.000000
mean    5000.50000      0.705600  10024.498524  402203.782224      0.033300
std     2886.89568      0.455795   5804.579486  160039.674988      0.179428
min        1.00000      0.000000      0.000000    9263.640000      0.000000
25%     2500.75000      0.000000   5780.790000  256085.520000      0.000000
50%     5000.50000      1.000000   9883.620000  414631.740000      0.000000
75%     7500.25000      1.000000  13995.660000  525692.760000      0.000000
max    10000.00000      1.000000  31851.840000  882650.760000      1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          10000 non-null  int64
 1   Employed       10000 non-null  int64
 2   Bank Balance   10000 non-null  float64
 3   Annual Salary  10000 non-null  float64
 4   Defaulted?     10000 non-null  int64
dtypes: float64(2), int64(3)
memory usage: 390.8 KB